In [25]:
# imports


import re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [14]:
data = pd.read_csv('Datasets/smartwatches.csv')

data.drop_duplicates(inplace=True)

train_df = data.sample(frac=0.8, random_state=42)
test_df = data.drop(train_df.index)

train_df = train_df.reset_index()
test_df = test_df.reset_index()

In [15]:
data.shape, train_df.shape, test_df.shape

((450, 16), (360, 17), (90, 17))

In [16]:
train_df.head()

,index,Unnamed: 0,Brand,Current Price,Original Price,Discount Percentage,Rating,Number OF Ratings,Model Name,Dial Shape,Strap Color,Strap Material,Touchscreen,Battery Life (Days),Bluetooth,Display Size,Weight
0,407,407,zebronics,2949.0,4199.0,29.768993,3.1,10.0,LEATHER fit-650,Oval,Black,Leather,Yes,NaN,Yes,2.7 inches,NaN
1,444,444,fire-boltt,6999.0,15999.0,56.253516,2.6,NaN,bsw020,Circle,Brown,Silicon,Yes,8.0,Yes,1.4 inches,NaN
2,117,117,fire-boltt,2499.0,11999.0,79.173264,4.1,1990.0,BSW070,NaN,NaN,NaN,Yes,8.0,Yes,1.9 inches,75g +
3,30,30,boat,1999.0,7990.0,74.981227,3.6,827.0,NaN,NaN,NaN,NaN,NaN,8.0,Yes,NaN,75g +
4,415,415,fire-boltt,2299.0,5999.0,61.676946,2.5,24.0,NINJA PRO MAX,Square,Blue,Silicon,Yes,22.0,Yes,1.6 inches,NaN

In [17]:
train_df.drop(['index','Unnamed: 0'], axis=1, inplace=True)
train_df.head()

,Brand,Current Price,Original Price,Discount Percentage,Rating,Number OF Ratings,Model Name,Dial Shape,Strap Color,Strap Material,Touchscreen,Battery Life (Days),Bluetooth,Display Size,Weight
0,zebronics,2949.0,4199.0,29.768993,3.1,10.0,LEATHER fit-650,Oval,Black,Leather,Yes,NaN,Yes,2.7 inches,NaN
1,fire-boltt,6999.0,15999.0,56.253516,2.6,NaN,bsw020,Circle,Brown,Silicon,Yes,8.0,Yes,1.4 inches,NaN
2,fire-boltt,2499.0,11999.0,79.173264,4.1,1990.0,BSW070,NaN,NaN,NaN,Yes,8.0,Yes,1.9 inches,75g +
3,boat,1999.0,7990.0,74.981227,3.6,827.0,NaN,NaN,NaN,NaN,NaN,8.0,Yes,NaN,75g +
4,fire-boltt,2299.0,5999.0,61.676946,2.5,24.0,NINJA PRO MAX,Square,Blue,Silicon,Yes,22.0,Yes,1.6 inches,NaN

In [18]:
train_df['Display Size'].isna().sum()

np.int64(27)

In [19]:
train_df['Display Size'].value_counts().count()

np.int64(34)

In [21]:
train_df['Display Size'].fillna('0.0 inches', inplace=True)
train_df['Display Size'].isna().sum()

np.int64(0)

In [ ]:
train_df['Display Size'].apply(lambda x: float(x.split()[0]))

# float('0.0 inches'.split()[0])

0.0

In [23]:
train_df['Weight'].value_counts()

Weight
20 - 35 g    63
75g +        58
35 - 50 g    45
<= 20 g      30
50 - 75 g    15
Name: count, dtype: int64

In [27]:
re.findall('\d+', '20 - 35 g')

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\bhave\AppData\Local\Temp\ipykernel_30992\3142025644.py:1: SyntaxWarning: invalid escape sequence '\d'
  re.findall('\d+', '20 - 35 g')

['20', '35']

In [28]:
cal = sum([int(x) for x in re.findall('\d+', '20 - 35 g')]) / 2

train_df['Weight'].replace('20 - 35 g', cal, inplace=True)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\bhave\AppData\Local\Temp\ipykernel_30992\2181387236.py:1: SyntaxWarning: invalid escape sequence '\d'
  cal = sum([int(x) for x in re.findall('\d+', '20 - 35 g')]) / 2

In [29]:
cal = sum([int(x) for x in re.findall('\d+', '35 - 50 g')]) / 2

train_df['Weight'].replace('35 - 50 g', cal, inplace=True)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\bhave\AppData\Local\Temp\ipykernel_30992\4170158647.py:1: SyntaxWarning: invalid escape sequence '\d'
  cal = sum([int(x) for x in re.findall('\d+', '35 - 50 g')]) / 2

In [30]:
cal = sum([int(x) for x in re.findall('\d+', '50 - 75 g')]) / 2

train_df['Weight'].replace('50 - 75 g', cal, inplace=True)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\bhave\AppData\Local\Temp\ipykernel_30992\2723606332.py:1: SyntaxWarning: invalid escape sequence '\d'
  cal = sum([int(x) for x in re.findall('\d+', '50 - 75 g')]) / 2

In [31]:
train_df['Weight'].replace('75g +', float(re.findall('\d+', '75g +')[0]), inplace=True)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\bhave\AppData\Local\Temp\ipykernel_30992\3271034506.py:1: SyntaxWarning: invalid escape sequence '\d'
  train_df['Weight'].replace('75g +', float(re.findall('\d+', '75g +')[0]), inplace=True)

In [32]:
train_df['Weight'].replace('<= 20 g', float(re.findall('\d+', '<= 20 g')[0]), inplace=True)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\bhave\AppData\Local\Temp\ipykernel_30992\1289372860.py:1: SyntaxWarning: invalid escape sequence '\d'
  train_df['Weight'].replace('<= 20 g', float(re.findall('\d+', '<= 20 g')[0]), inplace=True)
C:\Users\bhave\AppData\Local\Temp\ipykernel_30992\1289372860.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train_df['Weight'].replace('<= 20 g', float(re.findall('\d+', '<= 20 g')[0]), inplace=True)

In [33]:
train_df['Weight'].value_counts()

Weight
27.5    63
75.0    58
42.5    45
20.0    30
62.5    15
Name: count, dtype: int64

In [34]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Brand                360 non-null    object
 1   Current Price        354 non-null    float64
 2   Original Price       304 non-null    float64
 3   Discount Percentage  304 non-null    float64
 4   Rating               356 non-null    float64
 5   Number OF Ratings    315 non-null    float64
 6   Model Name           330 non-null    object
 7   Dial Shape           260 non-null    object
 8   Strap Color          260 non-null    object
 9   Strap Material       304 non-null    object
 10  Touchscreen          329 non-null    object
 11  Battery Life (Days)  330 non-null    float64
 12  Bluetooth            355 non-null    object
 13  Display Size         360 non-null    object
 14  Weight               211 non-null    float64
dtypes: float64(7), object(8)
memory usage: 42.3+ KB