In [25]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sb

In [26]:
data = pd.read_csv('smartwatches.csv', index_col=[0])
data.head()

,Brand,Current Price,Original Price,Discount Percentage,Rating,Number OF Ratings,Model Name,Dial Shape,Strap Color,Strap Material,Touchscreen,Battery Life (Days),Bluetooth,Display Size,Weight
0,noise,82990.0,89900.0,7.686318,4.0,65.0,Wrb-sw-colorfitpro4alpha-std-rgld_pnk,NaN,NaN,NaN,NaN,8.0,Yes,NaN,35 - 50 g
1,fire-boltt,3799.0,16999.0,77.651627,4.3,20788.0,BSW046,NaN,NaN,Silicon,Yes,3.5,Yes,1.8 inches,50 - 75 g
2,boat,1999.0,7990.0,74.981227,3.8,21724.0,Wave Call,NaN,NaN,Silicon,Yes,8.0,Yes,1.7 inches,35 - 50 g
3,fire-boltt,1799.0,19999.0,91.004550,4.3,13244.0,BSW053,NaN,NaN,Silicon,Yes,3.5,Yes,1.8 inches,75g +
4,noise,1599.0,4999.0,68.013603,4.1,13901.0,Wrb-sw-colorfitpulsegobuzz-std-blk_blk,NaN,NaN,Other,Yes,8.0,Yes,1.7 inches,35 - 50 g

In [27]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Brand                450 non-null    str
 1   Current Price        440 non-null    float64
 2   Original Price       377 non-null    float64
 3   Discount Percentage  377 non-null    float64
 4   Rating               444 non-null    float64
 5   Number OF Ratings    391 non-null    float64
 6   Model Name           415 non-null    str
 7   Dial Shape           327 non-null    str
 8   Strap Color          327 non-null    str
 9   Strap Material       381 non-null    str
 10  Touchscreen          413 non-null    str
 11  Battery Life (Days)  418 non-null    float64
 12  Bluetooth            444 non-null    str
 13  Display Size         420 non-null    str
 14  Weight               264 non-null    str
dtypes: float64(6), str(9)
memory usage: 52.9 KB

In [28]:
data.describe()

,Current Price,Original Price,Discount Percentage,Rating,Number OF Ratings,Battery Life (Days)
count,440.000000,377.000000,377.000000,444.000000,391.000000,418.000000
mean,12747.554545,14598.204244,48.236894,4.031306,11594.726343,14.077392
std,17760.666099,15450.028869,24.109830,0.550548,40423.889227,7.718503
min,1199.000000,1669.000000,-79.688436,1.000000,1.000000,0.750000
25%,2180.750000,5999.000000,33.337037,3.900000,68.500000,8.000000
50%,3999.000000,7999.000000,54.550414,4.100000,996.000000,17.500000
75%,17121.750000,17999.000000,66.677780,4.300000,6022.000000,22.000000
max,139990.000000,96390.000000,91.004550,5.000000,619130.000000,22.000000

In [29]:
pd.DataFrame({
    'Columns': data.columns,
    'Missing_values': [data[i].isna().sum() for i in data.columns],
    'duplicate_values': [data[i].duplicated().sum() for i in data.columns]
    
})

                Columns  Missing_values  duplicate_values
0                 Brand               0               432
1         Current Price              10               285
2        Original Price              73               345
3   Discount Percentage              73               178
4                Rating               6               422
5     Number OF Ratings              59               199
6            Model Name              35                60
7            Dial Shape             123               443
8           Strap Color             123               419
9        Strap Material              69               434
10          Touchscreen              37               447
11  Battery Life (Days)              32               442
12            Bluetooth               6               447
13         Display Size              30               409
14               Weight             186               444

In [30]:
# Change dtype of Display size

data.loc[:, "Display Size"] = data.loc[:,'Display Size'].str.strip('inches')
data['Display Size'] = data['Display Size'].astype('float')

In [31]:
# Imputing missing values on a Categorical col. based on most freq val in their respective Brand in each col.

categorical_mode = data.groupby('Brand')[
    data.select_dtypes(include='object') # select all col with dtype object
    .columns.drop(['Brand']) # excluding Brand
    ].agg(lambda x:x.mode().iloc[0] if not x.mode().empty else np.nan) # Impute a mode in each col

categorical_mode

C:\Users\bhave\AppData\Local\Temp\ipykernel_13412\421939513.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  data.select_dtypes(include='object') # select all col with dtype object

,Model Name,Dial Shape,Strap Color,Strap Material,Touchscreen,Bluetooth,Weight
Brand,,,,,,,
amazfit,Bip 3 Pro with 1.69 inch Large Color Display B...,Circle,Black,Silicon,Yes,Yes,<= 20 g
ambrane,FitShot Curl,Square,Black,Silicon,Yes,Yes,35 - 50 g
apple,Apple Watch SE,Rectangle,Black,Silicon,Yes,Yes,<= 20 g
boat,Watch Flash,Rectangle,Black,Silicon,Yes,Yes,35 - 50 g
crossbeats,S4 Max,NaN,NaN,NaN,Yes,Yes,20 - 35 g
dizo,D TALK SMART WATCH (SILVER GREY),Rectangle,Black,Silicon,Yes,Yes,20 - 35 g
fire-boltt,beast pro,Square,Black,Silicon,Yes,Yes,75g +
fitbit,Blaze,Square,Black,Silicon,Yes,Yes,20 - 35 g
fossil,4th Gen Explorist HR,Circle,Black,Stainless Steel,Yes,Yes,75g +
garmin,7.54E+11,Circle,Black,Silicon,Yes,Yes,20 - 35 g
gizmore,910,Square,Black,Silicon,Yes,Yes,75g +
hammer,NaN,NaN,NaN,NaN,NaN,Yes,75g +
honor,ARG-B39-cr,Circle,Black,Leather,Yes,Yes,20 - 35 g
huawei,Fit,Circle,Black,Silicon,Yes,Yes,75g +
noise,"Caliber Buzz Advanced BT Calling(True Sync), 1...",Rectangle,Black,Other,Yes,Yes,35 - 50 g
pebble,Aspire Unisex 2.5D Curved Screen Smartwatch wi...,Square,Black,Silicon,Yes,Yes,20 - 35 g
samsung,Galaxy Watch 3 41 mm,Circle,Black,Fluoroelastomer,Yes,Yes,20 - 35 g
zebronics,FIT380CH,Square,Black,Silicon,Yes,Yes,75g +

In [32]:
# Imputing missing values on Numerical col.

numerical_median = data.groupby('Brand')[
    data.select_dtypes(include = np.number)
    .columns].median()

numerical_median

,Current Price,Original Price,Discount Percentage,Rating,Number OF Ratings,Battery Life (Days),Display Size
Brand,,,,,,,
amazfit,8249.0,15999.0,29.585441,4.15,575.0,8.00,1.40
ambrane,1799.0,4999.0,60.542248,4.20,2475.0,22.00,1.70
apple,41900.0,31400.0,1.570780,4.60,2847.0,22.00,1.60
boat,1999.0,6990.0,74.263233,4.00,19590.0,22.00,1.70
crossbeats,3999.0,10999.0,63.338111,4.10,2426.0,5.80,1.85
dizo,2749.0,5999.0,47.510002,4.10,663.0,22.00,1.80
fire-boltt,3299.0,9999.0,65.006501,3.70,2571.0,22.00,1.45
fitbit,18849.0,22249.0,15.348749,4.60,396.5,10.50,1.30
fossil,14995.0,21995.0,39.405881,4.00,112.5,17.50,1.30
garmin,39490.0,44990.0,15.193720,4.60,19.0,17.50,1.20
gizmore,1999.0,5999.0,69.000009,4.00,69.5,5.75,1.60
hammer,1799.0,4999.0,64.012803,3.60,516.0,NaN,1.80
honor,10023.0,14999.0,26.505356,4.30,1445.0,12.50,1.40
huawei,14990.0,20990.0,40.020010,4.40,196.0,8.00,1.40
noise,1799.0,5999.0,64.012803,4.10,13901.0,8.00,1.70
pebble,3999.0,6999.0,43.563340,4.00,1176.0,12.50,1.10
samsung,24490.0,33999.0,18.609735,4.30,567.0,3.50,1.40
zebronics,2624.0,5999.0,56.011202,3.90,77.5,22.00,3.30

In [33]:
# fill all missing values with their respective brand mode and median

obj = 0
no = 0
# Not used because categorical col show str rather than object
# for col in data.columns.drop('Brand'): 
#     if data[col].dtype == 'o':
#         data[col] = data[col].fillna(data['Brand'].map(categorical_mode[col]))
#         obj+=1

#     elif np.issubdtype(data[col].dtype, np.number):
#         data[col] = data[col].fillna(data['Brand'].map(numerical_median[col]))
#         no += 1

for col in data.columns.drop('Brand'):
    if pd.api.types.is_string_dtype(data[col]):
        data[col] = data[col].fillna(data['Brand'].map(categorical_mode[col]))
        obj += 1
    elif pd.api.types.is_numeric_dtype(data[col]):
        data[col] = data[col].fillna(data['Brand'].map(numerical_median[col]))
        no += 1

print(f"Total number of object columns affected: {obj} \n"
    f"Total number of numeric columns affected: {no}")

Total number of object columns affected: 7
Total number of numeric columns affected: 7

In [34]:
data.head()

,Brand,Current Price,Original Price,Discount Percentage,Rating,Number OF Ratings,Model Name,Dial Shape,Strap Color,Strap Material,Touchscreen,Battery Life (Days),Bluetooth,Display Size,Weight
0,noise,82990.0,89900.0,7.686318,4.0,65.0,Wrb-sw-colorfitpro4alpha-std-rgld_pnk,Rectangle,Black,Other,Yes,8.0,Yes,1.7,35 - 50 g
1,fire-boltt,3799.0,16999.0,77.651627,4.3,20788.0,BSW046,Square,Black,Silicon,Yes,3.5,Yes,1.8,50 - 75 g
2,boat,1999.0,7990.0,74.981227,3.8,21724.0,Wave Call,Rectangle,Black,Silicon,Yes,8.0,Yes,1.7,35 - 50 g
3,fire-boltt,1799.0,19999.0,91.004550,4.3,13244.0,BSW053,Square,Black,Silicon,Yes,3.5,Yes,1.8,75g +
4,noise,1599.0,4999.0,68.013603,4.1,13901.0,Wrb-sw-colorfitpulsegobuzz-std-blk_blk,Rectangle,Black,Other,Yes,8.0,Yes,1.7,35 - 50 g

In [35]:
def check(data):
    dict={}
    for col in data.columns:
        dtype = data[col].dtypes
        valid_instances = data[col].count()
        unique = data[col].nunique()
        null_count = data[col].isnull().sum()
        duplicates = data[col].duplicated().sum()
        dict[col] = dtype,valid_instances,unique,null_count,duplicates
        data_check = pd.DataFrame(dict, index=["dtype","valid_instances","unique","sum_null","duplicates"]).T
    return data_check

check(data)

                       dtype valid_instances unique sum_null duplicates
Brand                    str             450     18        0        432
Current Price        float64             450    167        0        283
Original Price       float64             450    106        0        344
Discount Percentage  float64             450    276        0        174
Rating               float64             450     27        0        423
Number OF Ratings    float64             450    257        0        193
Model Name               str             449    389        1         60
Dial Shape               str             445      6        5        443
Strap Color              str             445     30        5        419
Strap Material           str             445     15        5        434
Touchscreen              str             449      2        1        447
Battery Life (Days)  float64             449      9        1        440
Bluetooth                str             450      2        0        448
Display Size         float64             450     40        0        410
Weight                   str             450      5        0        445

In [36]:
# remove duplicates
data.drop_duplicates(inplace=True)
data.reset_index(drop=True, inplace=True)

data.duplicated().sum() # 0

np.int64(0)

In [37]:
def check_unique(data):
    nunique = data.apply(lambda col: col.nunique())
    unique_values = data.apply(lambda col: col.unique())
    data_check = pd.DataFrame({
        'uni_count': nunique,
        'unique_values': unique_values
    })
    return data_check

check_unique(data)

,uni_count,unique_values
Brand,18,"[noise, fire-boltt, boat, honor, crossbeats, s..."
Current Price,167,"[82990.0, 3799.0, 1999.0, 1799.0, 1599.0, 1499..."
Original Price,106,"[89900.0, 16999.0, 7990.0, 19999.0, 4999.0, 39..."
Discount Percentage,276,"[7.686318131, 77.65162657, 74.98122653, 91.004..."
Rating,27,"[4.0, 4.3, 3.8, 4.1, 3.5, 4.2, 3.9, 3.6, 3.7, ..."
Number OF Ratings,257,"[65.0, 20788.0, 21724.0, 13244.0, 13901.0, 327..."
Model Name,389,"[Wrb-sw-colorfitpro4alpha-std-rgld_pnk, BSW046..."
Dial Shape,6,"[Rectangle, Square, Circle, nan, Curved, Conte..."
Strap Color,30,"[Black, nan, Midnight, Starlight Sport, Pink, ..."
Strap Material,15,"[Other, Silicon, Polycarbonate, Metal, Stainle..."
Touchscreen,2,"[Yes, nan, No]"
Battery Life (Days),9,"[8.0, 3.5, 3.6, 22.0, 12.5, 0.75, 17.5, 5.75, ..."
Bluetooth,2,"[Yes, No]"
Display Size,40,"[1.7, 1.8, 1.4, 1.9, 1.3, 1.5, 1.2, 4.6, 4.4, ..."
Weight,5,"[35 - 50 g, 50 - 75 g, 75g +, 20 - 35 g, <= 20 g]"

In [38]:
# Detecting Outliers

from tabulate import tabulate

outliers = {}

for col in data.select_dtypes(include=np.number).columns:
    q1 = data[col].quantile(0.25)
    q3 = data[col].quantile(0.75)
    iqr = q3-q1
    lower_bound = q1-1.5*iqr
    upper_bound = q3+1.5*iqr

    col_outliers = data[(data[col]>upper_bound) | (data[col]<lower_bound)]
    outliers[col] = col_outliers

print("Summary Stats for smartwatches:")
print(tabulate(data.describe(),headers='keys',tablefmt='pretty'))

for col, outlier_data in outliers.items():
    if len(outlier_data) == 0:
        continue
    else:
        print(f"Outliers in {col}", len(outlier_data))
        print(tabulate(outlier_data,headers='keys',tablefmt='pretty'))

Summary Stats for smartwatches:
+-------+--------------------+--------------------+---------------------+--------------------+--------------------+---------------------+--------------------+
|       |   Current Price    |   Original Price   | Discount Percentage |       Rating       | Number OF Ratings  | Battery Life (Days) |    Display Size    |
+-------+--------------------+--------------------+---------------------+--------------------+--------------------+---------------------+--------------------+
| count |       440.0        |       440.0        |        440.0        |       440.0        |       440.0        |        439.0        |       440.0        |
| mean  | 13104.452272727272 | 16906.979545454546 |  43.08094525723182  | 4.031818181818182  | 10133.967045454545 | 14.097038724373578  | 2.1470454545454545 |
|  std  | 17861.66489668709  | 15609.239458008176 | 25.131434293899545  | 0.5535854255296769 | 38193.19469981024  |  7.663339483067651  | 4.283388520655802  |
|  min  |       1199.0       |       1669.0       |    -79.68843619     |        1.0         |        1.0         |        0.75         |        0.0         |
|  25%  |      2298.75       |       5999.0       |    21.6245456575    |        3.9         |       76.125       |         8.0         |        1.3         |
|  50%  |       3999.0       |       9999.0       | 45.736006630000006  |        4.1         |       1016.0       |        17.5         |        1.6         |
|  75%  |      17999.0       |      22249.0       |     64.01280256     |        4.3         |       5193.5       |        22.0         |        1.8         |
|  max  |      139990.0      |      96390.0       |     91.00455023     |        5.0         |      619130.0      |        22.0         |        45.0        |
+-------+--------------------+--------------------+---------------------+--------------------+--------------------+---------------------+--------------------+
Outliers in Current Price 34
+-----+---------+---------------+----------------+---------------------+--------+-------------------+---------------------------------------------------------------------------------+------------+-----------------+-----------------+-------------+---------------------+-----------+--------------+-----------+
|     |  Brand  | Current Price | Original Price | Discount Percentage | Rating | Number OF Ratings |                                   Model Name                                    | Dial Shape |   Strap Color   | Strap Material  | Touchscreen | Battery Life (Days) | Bluetooth | Display Size |  Weight   |
+-----+---------+---------------+----------------+---------------------+--------+-------------------+---------------------------------------------------------------------------------+------------+-----------------+-----------------+-------------+---------------------+-----------+--------------+-----------+
|  0  |  noise  |    82990.0    |    89900.0     |     7.686318131     |  4.0   |       65.0        |                      Wrb-sw-colorfitpro4alpha-std-rgld_pnk                      | Rectangle  |      Black      |      Other      |     Yes     |         8.0         |    Yes    |     1.7      | 35 - 50 g |
| 57  | garmin  |    78490.0    |    89460.0     |     12.26246367     |  4.4   |        6.0        |                                    7.54E+11                                     |   Circle   |      Black      |     Silicon     |     Yes     |        17.5         |    Yes    |     1.2      |  <= 20 g  |
| 116 |  apple  |    89900.0    |    31400.0     |     1.570779866     |  4.7   |       51.0        |                           Watch Ultra GPS + Cellular                            | Rectangle  |  Orange Alpine  |     Fabric      |     Yes     |         3.5         |    Yes    |     1.9      |   75g +   |
| 117 |  apple  |    55900.0    |    31400.0     |     1.570779866     |  4.5   |       132.0       |                          Watch Series 8 GPS + Cellular                          | Rectangle  | Starlight Sport |     Silicon     |     Yes     |        22.0         |    Yes    |     1.6      |  <= 20 g  |
| 118 |  apple  |    44730.0    |    44900.0     |     0.378619154     |  4.6   |      2847.0       |     Watch Series7 (GPS, 45mm) - Green Aluminium Case with Clover Sport Band     | Rectangle  |      Green      |    Aluminium    |     Yes     |        22.0         |    Yes    |     1.8      | 20 - 35 g |
| 119 |  apple  |    41900.0    |    31400.0     |     1.570779866     |  4.6   |      2847.0       |     Watch Series7 (GPS, 41mm) - Green Aluminium Case with Clover Sport Band     | Rectangle  |      Green      |    Aluminium    |     Yes     |        22.0         |    Yes    |     1.6      |  <= 20 g  |
| 121 |  apple  |    49666.0    |    50900.0     |     2.424361493     |  4.5   |      1519.0       |  Watch Series7 (GPS + Cellular, 41mm)Blue Aluminium Case-Abyss Blue Sport Band  | Rectangle  |      Blue       |    Aluminium    |     Yes     |        22.0         |    Yes    |     1.6      |  <= 20 g  |
| 122 |  apple  |    53900.0    |    31400.0     |     1.570779866     |  4.5   |      1519.0       |  Watch Series7 (GPS + Cellular, 45mm)Blue Aluminium Case-Abyss Blue Sport Band  | Rectangle  |      Blue       |    Aluminium    |     Yes     |        22.0         |    Yes    |     1.8      | 20 - 35 g |
| 123 |  apple  |    49900.0    |    31400.0     |     1.570779866     |  4.5   |      1349.0       |                          Watch Series 6 GPS + Cellular                          | Rectangle  |      Black      |     Silicon     |     Yes     |        22.0         |    Yes    |     1.6      | 20 - 35 g |
| 124 |  apple  |    48900.0    |    31400.0     |     1.570779866     |  4.3   |       158.0       |                               Watch Series 8 GPS                                | Rectangle  | Starlight Sport |     Silicon     |     Yes     |        22.0         |    Yes    |     1.8      | 20 - 35 g |
| 129 |  apple  |    41900.0    |    31400.0     |     1.570779866     |  4.6   |      2847.0       |  Watch Series7 (GPS, 41mm) - Midnight Aluminium Case with Midnight Sport Band   | Rectangle  |      Black      |    Aluminium    |     Yes     |        22.0         |    Yes    |     1.6      |  <= 20 g  |
| 130 |  apple  |    53900.0    |    31400.0     |     1.570779866     |  4.5   |      1519.0       |     Watch Series7 (GPS+Cellular-45mm)Green Aluminium Case-Clover Sport Band     | Rectangle  |      Green      |    Aluminium    |     Yes     |        22.0         |    Yes    |     1.8      | 20 - 35 g |
| 131 |  apple  |    44900.0    |    31400.0     |     1.570779866     |  4.6   |      2847.0       |  Watch Series7 (GPS-45mm) (PRODUCT)RED Aluminium Case-(PRODUCT)RED Sport Band   | Rectangle  |       Red       |    Aluminium    |     Yes     |        22.0         |    Yes    |     1.8      | 20 - 35 g |
| 132 |  apple  |    44900.0    |    31400.0     |     1.570779866     |  4.6   |      2847.0       |   Watch Series7 (GPS, 45mm) - Blue Aluminium Case with Abyss Blue Sport Band    | Rectangle  |      Blue       |    Aluminium    |     Yes     |        22.0         |    Yes    |     1.8      | 20 - 35 g |
| 133 |  apple  |    41900.0    |    31400.0     |     1.570779866     |  4.6   |      2847.0       |   Watch Series7 (GPS, 41mm) - Blue Aluminium Case with Abyss Blue Sport Band    | Rectangle  |      Blue       |    Aluminium    |     Yes     |        22.0         |    Yes    |     1.6      |  <= 20 g  |
| 135 |  apple  |    41900.0    |    31400.0     |     1.570779866     |  4.6   |      2847.0       | Watch Series7 (GPS, 41mm) - Starlight Aluminium Case with Starlight Sport Band  | Rectangle  |      White      |    Aluminium    |     Yes     |        22.0         |    Yes    |     1.6      |  <= 20 g  |
| 137 |  apple  |    73900.0    |    31400.0     |     1.570779866     |  4.5   |      1519.0       | Watch Series7(GPS+Cellular, 41mm)-Gold Stainless Steel Case-Gold Milanese Loop  | Rectangle  |      Gold       | Stainless Steel |     Yes     |        22.0         |    Yes    |     1.6      |  <= 20 g  |
| 186 | samsung |    44999.0    |    48999.0     |     8.163431907     |  4.4   |       88.0        | Watch 5 pro 45mmSuper AMOLED displayBluetooth callingwith advanced GPS tracking |   Circle   |      Black      |     Rubber      |     Yes     |         3.5         |    Yes    |     1.4      | 20 - 35 g |
| 188 | samsung |    49999.0    |    54999.0     |     9.091074383     |  4.4   |       88.0        |    Watch 5 pro45mmSuper AMOLED displayLTE callingwith advanced GPS tracking     |   Circle   |      Grey       |     Rubber      |     Yes     |         3.5         |    Yes    |     1.4      | 20 - 35 g |
| 241 | garmin  |   139990.0    |    44990.0     |     15.19371993     |  4.7   |      6022.0       | Fenix 7X Sapphire Solar, Up to 28 days/37 days with solar*, Built in Flashlight |   Circle   |     Silver      | Stainless Steel |     Yes     |        17.5         |    Yes    |     0.1      | 20 - 35 g |
| 248 | garmin  |    89490.0    |    93990.0     |     4.787743377     |  4.7   |       19.0        | Fenix 7 Solar Multisport Watch, PacePro Technology, ClimbPro, Stamina Tracking  |   Circle   |      Black      |     Silicon     |     Yes     |        12.5         |    Yes    |     0.1      | 20 - 35 g |
| 249 | garmin  |    67490.0    |    44990.0     |     15.19371993     |  4.7   |       19.0        |   Forerunner 955 Solar charging upto 20 days, HRV & Stamina Status, Triathlon   |   Circle   |      White      |     Silicon     |     No      |         8.0         |    Yes    |     1.3      |   75g +   |
| 251 | garmin  |    98990.0    |    44990.0     |     15.19371993     |  4.7   |      6022.0       | Epix Gen 2, Sapphire, Up to 16 days Battery, AMOLED Display, Real Time Stamina  |   Circle   |      Black      |     Silicon     |     Yes     |        17.5         |    Yes    |     0.1      | 20 - 35 g |
| 252 | garmin  |    49990.0    |    51990.0     |     3.846893633     |  4.7   |       19.0        |                                  Approach S62                                   |   Circle   |      Black      |     Silicon     |     Yes     |         8.0         |    Yes    |     1.3      |   75g +   |
| 253 | garmin  |    44990.0    |    50490.0     |     10.89324619     |  4.0   |        6.0        |    Instinct 2 Solar, Rugged Outdoor SmartWatch, Multi GNSS, Tracback Routing    |   Circle   |      Blue       |     Silicon     |     No      |        17.5         |    Yes    |     0.9      | 20 - 35 g |
| 259 | garmin  |    89490.0    |    89990.0     |     0.555617291     |  4.7   |      6022.0       |      Epix Gen 2, Up to 16 days Battery, AMOLED Display, Real Time Stamina       |   Circle   |      Grey       |     Silicon     |     Yes     |        17.5         |    Yes    |     0.1      | 20 - 35 g |
| 260 | garmin  |    46990.0    |    44990.0     |     15.19371993     |  4.5   |        8.0        | Venu 2 Plus, AMOLED Display, Built in Speaker & MIC, Upto 9 Days Battery, SPO2  |   Circle   |      White      |     Silicon     |     Yes     |         3.5         |    Yes    |     1.3      |   75g +   |
| 261 | garmin  |    44990.0    |    46990.0     |     4.256224729     |  4.0   |        6.0        | Instinct 2 Solar, Battery Up to 28 days/Unlimited with solar*, Tracback Routing |   Circle   |      Black      |     Silicon     |     No      |        17.5         |    Yes    |     0.9      | 20 - 35 g |
| 262 | garmin  |    46990.0    |    62490.0     |     24.80396863     |  4.1   |       10.0        |       Forerunner 945, Premium GPS Running/Triathlon Smartwatch with Music       |   Circle   |      Black      |     Silicon     |     No      |         8.0         |    Yes    |     1.9      | 20 - 35 g |
| 265 | garmin  |    64990.0    |    82990.0     |     21.68936016     |  4.7   |       19.0        | Fenix 6S Sapphire, Premium GPS Watch, Music, Pace Guidance and Pulse Ox Sensors |   Circle   |      Black      |     Silicon     |     Yes     |        22.0         |    Yes    |     1.2      |   75g +   |
| 266 | garmin  |    44990.0    |    50490.0     |     10.89324619     |  4.7   |       19.0        | Instinct 2S Solar, Battery Upto 21 days/51 days with solar*, SPO2, HIIT workout |   Circle   |      Green      |     Silicon     |     No      |        17.5         |    Yes    |     0.8      | 20 - 35 g |
| 267 | garmin  |    76990.0    |    96390.0     |     20.12656915     |  4.7   |        7.0        | Fenix 6 Sapphire Carbon Gray DLC, Wrist-Based Heart Rate and Pulse OX, Sensors  |   Circle   |     Silver      |     Silicon     |     Yes     |        17.5         |    Yes    |     1.3      | 20 - 35 g |
| 268 | garmin  |    67490.0    |    67990.0     |     0.735402265     |  4.7   |      6022.0       |   Fenix 7 Multisport GPS Watch, Upto 18 Days Battery, Climbpro, Stamina, HRV    |   Circle   |      Grey       |     Silicon     |     Yes     |        12.5         |    Yes    |     0.1      | 20 - 35 g |
| 270 | garmin  |    50490.0    |    55990.0     |     9.823182711     |  4.7   |       109.0       |   Instinct 2 Solar, Tactical Rugged SmartWatch, Multi GNSS, Tracback Routing    |   Circle   |      Brown      |     Silicon     |     No      |        17.5         |    Yes    |     0.9      | 20 - 35 g |
+-----+---------+---------------+----------------+---------------------+--------+-------------------+---------------------------------------------------------------------------------+------------+-----------------+-----------------+-------------+---------------------+-----------+--------------+-----------+
Outliers in Original Price 18
+-----+---------+---------------+----------------+---------------------+--------+-------------------+---------------------------------------------------------------------------------+------------+-------------+----------------+-------------+---------------------+-----------+--------------+-----------+
|     |  Brand  | Current Price | Original Price | Discount Percentage | Rating | Number OF Ratings |                                   Model Name                                    | Dial Shape | Strap Color | Strap Material | Touchscreen | Battery Life (Days) | Bluetooth | Display Size |  Weight   |
+-----+---------+---------------+----------------+---------------------+--------+-------------------+---------------------------------------------------------------------------------+------------+-------------+----------------+-------------+---------------------+-----------+--------------+-----------+
|  0  |  noise  |    82990.0    |    89900.0     |     7.686318131     |  4.0   |       65.0        |                      Wrb-sw-colorfitpro4alpha-std-rgld_pnk                      | Rectangle  |    Black    |     Other      |     Yes     |         8.0         |    Yes    |     1.7      | 35 - 50 g |
| 53  | garmin  |    34990.0    |    51990.0     |     32.69859588     |  4.3   |       19.0        |                                 GM-010-02445-60                                 |   Circle   |    Black    | Carbon-Fiber;  |     Yes     |         8.0         |    Yes    |     1.2      | 35 - 50 g |
| 57  | garmin  |    78490.0    |    89460.0     |     12.26246367     |  4.4   |        6.0        |                                    7.54E+11                                     |   Circle   |    Black    |    Silicon     |     Yes     |        17.5         |    Yes    |     1.2      |  <= 20 g  |
| 121 |  apple  |    49666.0    |    50900.0     |     2.424361493     |  4.5   |      1519.0       |  Watch Series7 (GPS + Cellular, 41mm)Blue Aluminium Case-Abyss Blue Sport Band  | Rectangle  |    Blue     |   Aluminium    |     Yes     |        22.0         |    Yes    |     1.6      |  <= 20 g  |
| 186 | samsung |    44999.0    |    48999.0     |     8.163431907     |  4.4   |       88.0        | Watch 5 pro 45mmSuper AMOLED displayBluetooth callingwith advanced GPS tracking |   Circle   |    Black    |     Rubber     |     Yes     |         3.5         |    Yes    |     1.4      | 20 - 35 g |
| 188 | samsung |    49999.0    |    54999.0     |     9.091074383     |  4.4   |       88.0        |    Watch 5 pro45mmSuper AMOLED displayLTE callingwith advanced GPS tracking     |   Circle   |    Grey     |     Rubber     |     Yes     |         3.5         |    Yes    |     1.4      | 20 - 35 g |
| 246 | garmin  |    34990.0    |    51990.0     |     32.69859588     |  4.3   |        6.0        | Forerunner 745, GPS Multisport Watch, Training Stats, Advanced Running Dynamics |   Circle   |     Red     |    Silicon     |     No      |        22.0         |    Yes    |     1.2      | 20 - 35 g |
| 248 | garmin  |    89490.0    |    93990.0     |     4.787743377     |  4.7   |       19.0        | Fenix 7 Solar Multisport Watch, PacePro Technology, ClimbPro, Stamina Tracking  |   Circle   |    Black    |    Silicon     |     Yes     |        12.5         |    Yes    |     0.1      | 20 - 35 g |
| 252 | garmin  |    49990.0    |    51990.0     |     3.846893633     |  4.7   |       19.0        |                                  Approach S62                                   |   Circle   |    Black    |    Silicon     |     Yes     |         8.0         |    Yes    |     1.3      |   75g +   |
| 253 | garmin  |    44990.0    |    50490.0     |     10.89324619     |  4.0   |        6.0        |    Instinct 2 Solar, Rugged Outdoor SmartWatch, Multi GNSS, Tracback Routing    |   Circle   |    Blue     |    Silicon     |     No      |        17.5         |    Yes    |     0.9      | 20 - 35 g |
| 259 | garmin  |    89490.0    |    89990.0     |     0.555617291     |  4.7   |      6022.0       |      Epix Gen 2, Up to 16 days Battery, AMOLED Display, Real Time Stamina       |   Circle   |    Grey     |    Silicon     |     Yes     |        17.5         |    Yes    |     0.1      | 20 - 35 g |
| 261 | garmin  |    44990.0    |    46990.0     |     4.256224729     |  4.0   |        6.0        | Instinct 2 Solar, Battery Up to 28 days/Unlimited with solar*, Tracback Routing |   Circle   |    Black    |    Silicon     |     No      |        17.5         |    Yes    |     0.9      | 20 - 35 g |
| 262 | garmin  |    46990.0    |    62490.0     |     24.80396863     |  4.1   |       10.0        |       Forerunner 945, Premium GPS Running/Triathlon Smartwatch with Music       |   Circle   |    Black    |    Silicon     |     No      |         8.0         |    Yes    |     1.9      | 20 - 35 g |
| 265 | garmin  |    64990.0    |    82990.0     |     21.68936016     |  4.7   |       19.0        | Fenix 6S Sapphire, Premium GPS Watch, Music, Pace Guidance and Pulse Ox Sensors |   Circle   |    Black    |    Silicon     |     Yes     |        22.0         |    Yes    |     1.2      |   75g +   |
| 266 | garmin  |    44990.0    |    50490.0     |     10.89324619     |  4.7   |       19.0        | Instinct 2S Solar, Battery Upto 21 days/51 days with solar*, SPO2, HIIT workout |   Circle   |    Green    |    Silicon     |     No      |        17.5         |    Yes    |     0.8      | 20 - 35 g |
| 267 | garmin  |    76990.0    |    96390.0     |     20.12656915     |  4.7   |        7.0        | Fenix 6 Sapphire Carbon Gray DLC, Wrist-Based Heart Rate and Pulse OX, Sensors  |   Circle   |   Silver    |    Silicon     |     Yes     |        17.5         |    Yes    |     1.3      | 20 - 35 g |
| 268 | garmin  |    67490.0    |    67990.0     |     0.735402265     |  4.7   |      6022.0       |   Fenix 7 Multisport GPS Watch, Upto 18 Days Battery, Climbpro, Stamina, HRV    |   Circle   |    Grey     |    Silicon     |     Yes     |        12.5         |    Yes    |     0.1      | 20 - 35 g |

In [39]:

pd.reset_option('display.max_rows')

outliers.get('Display Size').sort_values('Display Size', ascending=False)

,Brand,Current Price,Original Price,Discount Percentage,Rating,Number OF Ratings,Model Name,Dial Shape,Strap Color,Strap Material,Touchscreen,Battery Life (Days),Bluetooth,Display Size,Weight
296,fossil,18995.0,21995.0,39.405881,4.0,102.0,Wander RG,Circle,Black,Silicon,Yes,22.0,Yes,45.0,75g +
50,garmin,39490.0,44990.0,15.193720,3.7,6.0,7.54E+11,Circle,Black,Silicon,Yes,22.0,Yes,35.9,35 - 50 g
52,garmin,39490.0,44990.0,15.193720,5.0,1.0,7.54E+11,Circle,Black,Silicon,Yes,22.0,Yes,35.9,35 - 50 g
247,garmin,39490.0,41990.0,5.953799,4.8,6.0,"Venu 2, GPS Smartwatch, AMOLED Display, Upto 1...",Circle,Blue,Silicon,Yes,17.5,Yes,33.0,20 - 35 g
54,garmin,39490.0,44990.0,15.193720,3.8,38.0,7.54E+11,Circle,Black,Stainless Steel,Yes,8.0,Yes,30.0,75g +
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,fire-boltt,3599.0,9999.0,64.006401,3.7,2571.0,ring,Square,Blue,Rubber,Yes,22.0,Yes,0.1,75g +
438,fire-boltt,3200.0,7999.0,59.994999,3.7,2571.0,call 2,Square,Blue,Silicon,Yes,22.0,Yes,0.1,75g +
436,fire-boltt,3700.0,9999.0,62.996300,3.7,2571.0,beast pro,Square,Black,Silicon,Yes,8.0,Yes,0.1,75g +
439,fire-boltt,3000.0,7999.0,62.495312,3.7,2571.0,call 2,Square,Black,Silicon,Yes,22.0,Yes,0.1,75g +
379,pebble,5190.0,7499.0,30.790772,4.1,1176.0,Venus Bluetooth Calling Smartwatch with Fitnes...,Circle,Black,Silicon,Yes,12.5,Yes,0.0,20 - 35 g

In [40]:
import plotly.express as px
fig = px.box(data_frame=data.select_dtypes(include=np.number),orientation="v")

fig.show()

In [41]:
data.head()

,Brand,Current Price,Original Price,Discount Percentage,Rating,Number OF Ratings,Model Name,Dial Shape,Strap Color,Strap Material,Touchscreen,Battery Life (Days),Bluetooth,Display Size,Weight
0,noise,82990.0,89900.0,7.686318,4.0,65.0,Wrb-sw-colorfitpro4alpha-std-rgld_pnk,Rectangle,Black,Other,Yes,8.0,Yes,1.7,35 - 50 g
1,fire-boltt,3799.0,16999.0,77.651627,4.3,20788.0,BSW046,Square,Black,Silicon,Yes,3.5,Yes,1.8,50 - 75 g
2,boat,1999.0,7990.0,74.981227,3.8,21724.0,Wave Call,Rectangle,Black,Silicon,Yes,8.0,Yes,1.7,35 - 50 g
3,fire-boltt,1799.0,19999.0,91.004550,4.3,13244.0,BSW053,Square,Black,Silicon,Yes,3.5,Yes,1.8,75g +
4,noise,1599.0,4999.0,68.013603,4.1,13901.0,Wrb-sw-colorfitpulsegobuzz-std-blk_blk,Rectangle,Black,Other,Yes,8.0,Yes,1.7,35 - 50 g

In [ ]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
data[data.columns[data.eq("Yes").any()]] # equivalent to data[['Touchscreen', 'Bluetooth']]

    Touchscreen Bluetooth
0           Yes       Yes
1           Yes       Yes
2           Yes       Yes
3           Yes       Yes
4           Yes       Yes
..          ...       ...
435         Yes       Yes
436         Yes       Yes
437         Yes       Yes
438         Yes       Yes
439         Yes       Yes

[440 rows x 2 columns]

In [43]:
for col in data.columns[data.eq("Yes").any()]:
    le.fit(data[col])
    data[col] = le.transform(data[col])

In [48]:
pd.set_option('display.max_colwidth', None)